test_file: '/home/woody/iwi5/iwi5362h/data/vindr_cxr/annotations/image_labels_test.csv'
disease_book: '/home/woody/iwi5/iwi5362h/MedKLIP/zero_shot_vindr/observation_explanation.json'

image_res: 224
test_batch_size: 64

d_model: 256
res_base_model: 'resnet50'
num_queries: 75
dropout: 0.1
attribute_set_size: 2
N: 4
H: 4
text_encoder: 'emilyalsentzer/Bio_ClinicalBERT'



